Repository googleapis/java-scheduler, pull requests merged in 2020-09, with the labels that each got.

#208 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: cloudscheduler, cla: yes, context: full

#214 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudscheduler, cla: yes, context: full

#215 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#225 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#226 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#227 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: cloudscheduler, automerge, cla: yes

#232 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#234 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
