Repository googleapis/java-scheduler, pull requests merged in 2020-06, with the labels that each got.

#151 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#143 fix: restore GAPIC v2 retry configs
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/CloudSchedulerClient.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/CloudSchedulerSettings.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/package-info.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/stub/CloudSchedulerStub.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/stub/CloudSchedulerStubSettings.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/stub/GrpcCloudSchedulerStub.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerClient.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerSettings.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/package-info.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/CloudSchedulerStub.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/CloudSchedulerStubSettings.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/GrpcCloudSchedulerStub.java
  google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1/CloudSchedulerClientTest.java
  google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#154 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#153 chore: regenerate with updated protoc
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/AppEngineHttpTarget.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/AppEngineRouting.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/CreateJobRequest.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/DeleteJobRequest.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/GetJobRequest.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/HttpMethod.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/HttpTarget.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/Job.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ListJobsRequest.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ListJobsResponse.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/OAuthToken.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/OidcToken.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/PauseJobRequest.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/PubsubTarget.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ResumeJobRequest.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/RetryConfig.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/RunJobRequest.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/UpdateJobRequest.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineHttpTarget.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/AppEngineRouting.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/CreateJobRequest.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/DeleteJobRequest.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/GetJobRequest.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/HttpMethod.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/HttpTarget.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/Job.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsRequest.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ListJobsResponse.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/OAuthToken.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/OidcToken.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/PauseJobRequest.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/PubsubTarget.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ResumeJobRequest.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/RetryConfig.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/RunJobRequest.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/UpdateJobRequest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#156 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#158 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#163 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#167 fix: migrate scheduler/v1beta1 to grpc_service_config
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerClient.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerSettings.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/package-info.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/CloudSchedulerStub.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/CloudSchedulerStubSettings.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/GrpcCloudSchedulerStub.java
  google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#168 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#172 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#174 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-scheduler/pom.xml
  grpc-google-cloud-scheduler-v1/pom.xml
  grpc-google-cloud-scheduler-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-scheduler-v1/pom.xml
  proto-google-cloud-scheduler-v1beta1/pom.xml
Labels: cla: yes

#186 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
