Repository googleapis/java-scheduler, pull requests merged in 2021-03, with the labels that each got.

#369 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, automerge, cla: yes

#370 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, automerge, cla: yes

#371 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: cloudscheduler, automerge, cla: yes, context: full

#373 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, automerge, cla: yes

#374 chore(release): update Java microgenerator to 1.0.1
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/CloudSchedulerClient.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/CloudSchedulerSettings.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/package-info.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/stub/CloudSchedulerStub.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/stub/CloudSchedulerStubSettings.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/stub/GrpcCloudSchedulerCallableFactory.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/stub/GrpcCloudSchedulerStub.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerClient.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerSettings.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/package-info.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/CloudSchedulerStub.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/CloudSchedulerStubSettings.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/GrpcCloudSchedulerCallableFactory.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/stub/GrpcCloudSchedulerStub.java
  google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1/CloudSchedulerClientTest.java
  google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1/MockCloudScheduler.java
  google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1/MockCloudSchedulerImpl.java
  google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerClientTest.java
  google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1beta1/MockCloudScheduler.java
  google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1beta1/MockCloudSchedulerImpl.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/JobName.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/LocationName.java
  proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/TopicName.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/JobName.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/LocationName.java
  proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/TopicName.java
  synth.metadata
Labels: api: cloudscheduler, automerge, cla: yes, context: full

#376 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, cla: yes

#377 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, automerge, cla: yes

#378 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudscheduler, automerge, cla: yes, context: full

#379 chore: update gax-java dependency to 1.62
  grpc-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/CloudSchedulerGrpc.java
  grpc-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerGrpc.java
  synth.metadata
Labels: api: cloudscheduler, automerge, cla: yes, context: full

#381 deps: update dependency com.google.cloud:google-cloud-shared-dependencies to v0.20.1
  .kokoro/dependencies.sh
  pom.xml
Labels: api: cloudscheduler, automerge, cla: yes

#383 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudscheduler, automerge, cla: yes, context: full

#386 chore: update java microgenerator to 1.0.2 Adds request initialization to sample code
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1/CloudSchedulerClient.java
  google-cloud-scheduler/src/main/java/com/google/cloud/scheduler/v1beta1/CloudSchedulerClient.java
  google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1/MockCloudSchedulerImpl.java
  google-cloud-scheduler/src/test/java/com/google/cloud/scheduler/v1beta1/MockCloudSchedulerImpl.java
  synth.metadata
Labels: api: cloudscheduler, automerge, cla: yes, context: full, samples

#387 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, automerge, cla: yes

#390 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, automerge, cla: yes

#392 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, automerge, cla: yes

#393 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudscheduler, automerge, build.sh, cla: yes, context: full, in, sample-secrets, samples

#394 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, automerge, cla: yes

#395 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: cloudscheduler, automerge, cla: yes, context: full
