Repository googleapis/java-scheduler, pull requests merged in 2021-05, with the labels that each got.

#430 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: cloudscheduler, automerge, cla: yes, context: none

#431 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: cloudscheduler, automerge, cla: yes

#432 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudscheduler, cla: yes, context: full

#437 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, automerge, cla: yes

#438 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, automerge, cla: yes

#439 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: cloudscheduler, automerge, cla: yes, context: full

#445 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, automerge

#448 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, automerge, cla: yes

#449 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudscheduler, automerge, cla: yes, context: full

#451 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: cloudscheduler, automerge, cla: yes, context: full

#454 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudscheduler, automerge, cla: yes, context: full

#457 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, automerge, cla: yes

#461 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, automerge, cla: yes

#462 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudscheduler, automerge, cla: yes
